### ISSUE TITLE
findBy criteria field names

### ISSUE THREAD

**Issue by l-vo** [doctrine/skeleton-mapper#23]
Hello,

I'm a bit surprised by the implementation of `findBy` (and `findOneBy`) in `Doctrine\SkeletonMapper\DataRepository\ArrayObjectDataRepository`. It seems this method is designed to be called with the field names of the storage layer. Shouldn't it use the object field names instead ?

For instance, let's look at the `User` class used in the tests:
```php
class User extends BaseObject
{
    private $id;  // _id in the storage layer
    private $username;
    private $password;
    private $profile; // profileId in the storage layer
    private $groups; // groupIds in the storage layer
    // ...
}
```

So to find by profile with `ArrayObjectDataRepository`:
```php
$repository->findBy(['profileId' => $profile]);
```

This sounds strange to me since in Doctrine ORM, the way to use `findBy` is:
```php
$repository->findBy(['profile' => $profile]);
```

**Comment by jwage** [comment]
The implementation details of everything are left up to you. The `ArrayObjectDataRepository` implementation is just a simple example to demonstrate persisting and hydrating objects from data stored in a PHP array. There are no concepts of relationships or anything at this level.

**Comment by l-vo** [comment]
It makes sense, thank you for your answer :)
